export const TEMPLATE_COLUMNS_SHOW = 'TEMPLATE_COLUMNS_SHOW';
export const TEMPLATE_COLUMNS_HIDE = 'TEMPLATE_COLUMNS_HIDE';
export const ADD_TEMPLATE_LANGUAGE = 'ADD_TEMPLATE_LANGUAGE';
export const REMOVE_TEMPLATE_LANGUAGE = 'REMOVE_TEMPLATE_LANGUAGE';
export const SECOND_LANGUAGE = 'SECOND_LANGUAGE';
export const TYPE_OF_VIEW = 'TYPE_OF_VIEW';
export const CHECK_ROW = 'CHECK_ROW';
export const UNCHECK_ROW = 'UNCHECK_ROW';
