import HeaderNavigation from '@/components/navigation/HeaderNavigation';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<HeaderNavigation />
				{children}
			</body>
		</html>
	);
}
